version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  webhook-server:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    environment:
      - GITHUB_SECRET=a7sd98f7a9sd8f7a9s8df7a9sdf7
    ports:
      - "5001:5001"
    restart: always
